name: DevSecOps CI Pipeline

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-and-build:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run SAST Security Scan (Semgrep)
        run: semgrep scan --config p/security-audit --config p/secrets --config .semgrep/rules.yml --error
