name: DevSecOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Full SAST Security Scan (Semgrep)
        run: |
          pip install semgrep
          semgrep scan --config="p/security-audit" --config="p/secrets" --error
